// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuikProject.Data;

namespace TuikProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.CezaInfazKurumlarıSayıKapasiteBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CezaInfazKurumlarıSayıKapasiteBilgileri");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.CezaInfazKurumuCinsiyetStatuUyluk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CezaInfazKurumuCinsiyetStatuUyluk");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.CezaInfazKurumunaGirdigiAndakiYasGrubunaGore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CezaInfazKurumunaGirdigiAndakiYasGrubunaGore");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.EgitimDurumunaGoreGirenHukumluler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EgitimDurumunaGoreGirenHukumluler");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.MedeniDurumaGoreGirenHukumluler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedeniDurumaGoreGirenHukumluler");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.SucIslenenYasGrubunaGoreGirenHukumluler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SucIslenenYasGrubunaGoreGirenHukumluler");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.SucTuruVeEgitimDurumunaGoreGirenHukumluler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bilinmeyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilkogretim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilkokul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lisedengimeslekokulu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Okumayazmabilmeyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Okuryazarokulbitirmeyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ortaokuldengimeslekokulu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yuksekogretim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SucTuruVeEgitimDurumunaGoreGirenHukumluler");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.SucTuruneGoreGirenHukumluler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OranErkek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OranKadin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OranToplam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SayiErkek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SayiKadin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SayiToplam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SucTuruneGoreGirenHukumluler");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.YuzBinNufusaDusenCezaInfazKurumuNufusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YuzBinNufusaDusenCezaInfazKurumuNufusu");
                });

            modelBuilder.Entity("TuikProject.Models.CezaInfazKurumuIstatistikleriModels.YılIcindeGirenVeCikanHukumluler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sayi2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YılIcindeGirenVeCikanHukumluler");
                });

            modelBuilder.Entity("TuikProject.Models.IssizlikOraniModels.SosyalGüvenlikKuruluşunaKayitlilik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErkekIstihdam2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErkekIstihdam2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErkekKayitdisi2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErkekKayitdisi2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErkekKayitdisiOrani2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErkekKayitdisiOrani2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadinIstihdam2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadinIstihdam2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadinKayitdisi2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadinKayitdisi2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadinKayitdisiOrani2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadinKayitdisiOrani2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamIstihdam2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamIstihdam2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamKayitdisi2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamKayitdisi2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamKayitdisiOrani2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamKayitdisiOrani2020")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SosyalGüvenlikKuruluşunaKayitlilik");
                });

            modelBuilder.Entity("TuikProject.Models.IssizlikOraniModels.İştekiDurumVeEkonomikFaaliyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Erkek2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Erkek2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErkekOran2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErkekOran2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kadin2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kadin2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadinOran2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadinOran2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2020")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamOran2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamOran2020")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("İştekiDurumVeEkonomikFaaliyet");
                });

            modelBuilder.Entity("TuikProject.Models.KulturEkonomisiModels.HarcamaTurlerineGoreHanehalkininHarcamalari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Harcama2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Harcama2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HarcamaTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HarcamaTurlerineGoreHanehalkininHarcamalari");
                });

            modelBuilder.Entity("TuikProject.Models.KulturEkonomisiModels.KulturHarcamalari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Harcama2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Harcama2019Mtl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oran2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KulturHarcamalari");
                });

            modelBuilder.Entity("TuikProject.Models.KulturEkonomisiModels.KulturelAlanlaraGoreGenelDevletHarcamasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CariHarcama2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariHarcama2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diger2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diger2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KulturelAlanlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SermayeHarcama2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SermayeHarcama2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KulturelAlanlaraGoreGenelDevletHarcamasi");
                });

            modelBuilder.Entity("TuikProject.Models.KulturEkonomisiModels.KulturelAlanlaraGoreMahalliIdarelerHarcamasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CariHarcama2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariHarcama2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KulturelAlanlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SermayeHarcama2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SermayeHarcama2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KulturelAlanlaraGoreMahalliIdarelerHarcamasi");
                });

            modelBuilder.Entity("TuikProject.Models.KulturEkonomisiModels.KulturelAlanlaraGoreMalIhracatVeIthalati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElSanatlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GorselIsitselMedya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GorselSanatlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GosteriSanatlariOrtakKutlama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KitapYaziliBasin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KulturelMirasArsivKutuphane")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MimarlikTasarimUrunler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KulturelAlanlaraGoreMalIhracatVeIthalati");
                });

            modelBuilder.Entity("TuikProject.Models.KulturEkonomisiModels.KulturelAlanlaraGoreMerkeziDevletHarcamasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CariHarcama2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariHarcama2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diger2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diger2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KulturelAlanlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SermayeHarcama2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SermayeHarcama2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KulturelAlanlaraGoreMerkeziDevletHarcamasi");
                });

            modelBuilder.Entity("TuikProject.Models.KulturEkonomisiModels.KulturelMalDisTicaretiVeDegisimOrani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IH_AnaMal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IH_IkinciMal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IH_KulturelMalIhracatAnaMal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IH_KulturelMalIhracatIkinciMal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IH_KulturelMalIhracatToplam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IH_KulturelMalIhracatToplamIhracat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IH_Toplam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IH_ToplamIhracat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_AnaMal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_IkinciMal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_KulturelMalIthalatAnaMal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_KulturelMalIthalatIkinciMal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_KulturelMalIthalatToplam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_KulturelMalIthalatToplamIthalat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_Toplam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_ToplamIthalat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KulturelMalDisTicaretiVeDegisimOrani");
                });

            modelBuilder.Entity("TuikProject.Models.KulturEkonomisiModels.KulturelSektorlereGoreBaziTemelGostergeler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CalisanSayisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CiroBinTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GirisimSayisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KatmaDeger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KulturelSektorler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KulturelSektorlereGoreBaziTemelGostergeler");
                });

            modelBuilder.Entity("TuikProject.Models.SaglikHarcamalariIstatistikleriModels.SaglikHarcamalarininGenelToplamDagilimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diger2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diger2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenelToplam2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenelToplam2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hanehalklari2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hanehalklari2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MahalliIdareler2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MahalliIdareler2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerkeziDevlet2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerkeziDevlet2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGK2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGK2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigortasirket2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigortasirket2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam22018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam22019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SaglikHarcamalarininGenelToplamDagilimi");
                });

            modelBuilder.Entity("TuikProject.Models.SaglikHarcamalariIstatistikleriModels.SaglikHizmetiSunucularinaGoreHarcamalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diger2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diger2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenelToplam2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenelToplam2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hanehalklari2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hanehalklari2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MahalliIdareler2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MahalliIdareler2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerkeziDevlet2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerkeziDevlet2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGK2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGK2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigortasirket2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigortasirket2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam22018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam22019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SaglikHizmetiSunucularinaGoreHarcamalar");
                });

            modelBuilder.Entity("TuikProject.Models.SosyalKorumaIstatistikleriModels.AyniVeNakdiYardimlarinGruplaraGoreDagilimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AyniYardim2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AyniYardim2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NakdiYardim2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NakdiYardim2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamYardim2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamYardim2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AyniVeNakdiYardimlarinGruplaraGoreDagilimi");
                });

            modelBuilder.Entity("TuikProject.Models.SosyalKorumaIstatistikleriModels.GruplaraGoreBrutVeNetSosyalKorumaHarcamaları", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brut2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brut22018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Net2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Net22019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GruplaraGoreBrutVeNetSosyalKorumaHarcamaları");
                });

            modelBuilder.Entity("TuikProject.Models.SosyalKorumaIstatistikleriModels.SartliVeSartsizYardimlarinGruplaraGoreDagilimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SartliYardim2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SartliYardim2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SartsizYardim2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SartsizYardim2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamYardim2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplamYardim2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SartliVeSartsizYardimlarinGruplaraGoreDagilimi");
                });

            modelBuilder.Entity("TuikProject.Models.SosyalKorumaIstatistikleriModels.SosyalKorumaGelirlerininTurlerineGore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SosyalKorumaGelirlerininTurlerineGore");
                });

            modelBuilder.Entity("TuikProject.Models.SosyalKorumaIstatistikleriModels.SosyalKorumaKapsamindaYardimAlanSayisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Erkek2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Erkek2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kadin2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kadin2019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toplam2019")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SosyalKorumaKapsamindaYardimAlanSayisi");
                });

            modelBuilder.Entity("TuikProject.Models.TüketiciFiyatEndeksiModels.AnaHarcamaGruplari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agirliklari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AralikDegisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AylikDegisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endeks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HarcamaGruplari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrtalamayaGoreDegisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YillikDegisim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnaHarcamaGruplari");
                });

            modelBuilder.Entity("TuikProject.Models.TüketiciFiyatEndeksiModels.TüketiciFiyatEndeksiVeDeğişimOranları", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agustos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aralik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ekim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eylul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haziran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kasim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mayis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nisan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temmuz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TüketiciFiyatEndeksiVeDeğişimOranları");
                });

            modelBuilder.Entity("TuikProject.Models.TüketiciFiyatEndeksiModels.İstatistikiBolgeBirimleriSiniflamasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AralikDegisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AylikDegisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endeks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrtalamayaGoreDegisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YillikDegisim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("İstatistikiBolgeBirimleriSiniflamasi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
